### ISSUE TITLE
Convert Configurations

### ISSUE THREAD

**Issue by okpatil4u** [qiushiyan/ios-transformers#1]
Hello @qiushiyan,

Great work btw !

Can you put a requirement.txt with specific versions of coremltools, tensorflow and transformers which you used ?

I haven't been able to run the distilbert.py script.

**Comment by qiushiyan** [comment]
Sure, I just added [here](https://github.com/qiushiyan/ios-transformers/blob/main/convert/requirements.txt)

**Comment by okpatil4u** [comment]
Thanks man ! I was able to getting it running !

Closing this issue.
